<template>
  <TopNavFour />

  <div>
    <h1>ACM Leaderboard</h1>
    <Board :leaderboard="leaderboardData" :problems="problemNames" />
  </div>
</template>

<script setup>
import { ref , onMounted} from "vue";
import { useRoute, useRouter } from "vue-router"
import { getContestBoardService, getContestProblemCalculateService } from "@/api/contest.js"
import TopNavFour from "../../components/TopNavFour.vue"
import Board  from "./components/Board.vue";
// ############################

// 示例排行榜数据
const leaderboardData = ref([
  {
    place: 1,
    school: '清华大学',
    teamName: 'Team Alpha',
    solved: 5,
    penalty: 1234,
    problems: [
      { time: 250, penalty: '+3' },
      { time: 60, penalty: '+1' },
      { time: 52, penalty: '+1' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '12.5%',
  },
  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },  {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },{
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  }, {
    place: 2,
    school: '北京大学',
    teamName: 'Team Beta',
    solved: 4,
    penalty: 2345,
    problems: [
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 180, penalty: '+2' },
      { time: 100, penalty: '+1' },
      { time: 88, penalty: '+3' },
      { time: 88, penalty: '+3' },
      // 其他题目...
    ],
    dirt: '20.0%',
  },
]);

// 示例题目名称
const problemNames = ref(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M']);




// ############################


const route = useRoute()
const router = useRouter()

// 模拟的题目数据，包含每个题目的名称和通过的队伍数量
const problems = ref([
  { name: "A", solvedBy: 2 },
  { name: "B", solvedBy: 2 },
  { name: "C", solvedBy: 1 },
  { name: "D", solvedBy: 3 },
  { name: "E", solvedBy: 0 },
  { name: "F", solvedBy: 0 },
  { name: "G", solvedBy: 0 },
  { name: "H", solvedBy: 2 },
  { name: "I", solvedBy: 2 },
  { name: "J", solvedBy: 1 },
  { name: "K", solvedBy: 3 },
  { name: "L", solvedBy: 0 },
  { name: "M", solvedBy: 0 },
  { name: "N", solvedBy: 0 },
]);

// 模拟的榜单数据
const boardData = ref([
  {
    rank: 1,
    name: "Team Alpha",
    score: 5,
    penalty: 45,
    results: {
      A: { submissions: 1, passed: true, time: "120" },
      B: { submissions: 2, passed: false, time: "" },
      C: { submissions: 3, passed: true, time: "52" },
      D: { submissions: 1, passed: true, time: "10" },
      E: { submissions: 0, passed: false, time: "" },
      F: { submissions: 0, passed: false, time: "" },
      G: { submissions: 0, passed: false, time: "" },
      H: { submissions: 1, passed: true, time: "120" },
      I: { submissions: 2, passed: false, time: "" },
      J: { submissions: 3, passed: true, time: "52" },
      K: { submissions: 1, passed: true, time: "10" },
      L: { submissions: 0, passed: false, time: "" },
      M: { submissions: 0, passed: false, time: "" },
      N: { submissions: 0, passed: false, time: "" },
    },
    dirt: 36,
    se: 0.44,
  },
  {
    rank: 2,
    name: "Team Beta",
    score: 4,
    penalty: 30,
    results: {
      A: { submissions: 1, passed: true, time: "120" },
      B: { submissions: 2, passed: false, time: "" },
      C: { submissions: 3, passed: true, time: "52" },
      D: { submissions: 1, passed: true, time: "10" },
      E: { submissions: 0, passed: false, time: "" },
      F: { submissions: 0, passed: false, time: "" },
      G: { submissions: 0, passed: false, time: "" },
      H: { submissions: 1, passed: true, time: "120" },
      I: { submissions: 2, passed: false, time: "" },
      J: { submissions: 3, passed: true, time: "52" },
      K: { submissions: 1, passed: true, time: "10" },
      L: { submissions: 0, passed: false, time: "" },
      M: { submissions: 0, passed: false, time: "" },
      N: { submissions: 0, passed: false, time: "" },
    },
    dirt: 36,
    se: 0.44,
  },
  {
    rank: 3,
    name: "Team Gamma",
    score: 4,
    penalty: 50,
    results: {
      A: { submissions: 1, passed: true, time: "120" },
      B: { submissions: 2, passed: false, time: "" },
      C: { submissions: 3, passed: true, time: "52" },
      D: { submissions: 1, passed: true, time: "10" },
      E: { submissions: 0, passed: false, time: "" },
      F: { submissions: 0, passed: false, time: "" },
      G: { submissions: 0, passed: false, time: "" },
      H: { submissions: 1, passed: true, time: "120" },
      I: { submissions: 2, passed: false, time: "" },
      J: { submissions: 3, passed: true, time: "52" },
      K: { submissions: 1, passed: true, time: "10" },
      L: { submissions: 0, passed: false, time: "" },
      M: { submissions: 0, passed: false, time: "" },
      N: { submissions: 0, passed: false, time: "" },
    },
    dirt: 36,
    se: 0.44,
  },
]);

// 分页组件细节
const currentPage = ref(1);
const pageSize = ref(50)
const total = ref(0)

// 弹窗控制变量
const dialogVisible = ref(false);
const dialogData = ref([]);

const teamNameSelected = ref()
const schoolSelected = ref()

// 显示题目列的标签，并添加通过的队伍数量
const problemLabel = (problem) => {
  return `${problem.name} (${problem.solvedBy})`;
};

// 根据是否通过返回不同的样式类
const getCellClass = (passed) => {
  return passed ? "passed" : "not-passed";
};

// 打开弹窗并设置选中的详细信息
const openDialog = (row, problem) => {
  dialogData.value = [
    { label: "Problem", value: problem.name },
    { label: "Team", value: row.name },
    {
      label: "Status",
      value: row.results[problem.name].passed ? "Passed" : "Failed",
    },
    { label: "Submit Time", value: row.results[problem.name].time || "N/A" },
  ];
  dialogVisible.value = true;
};

// 返回颜色
const getProblemColor = (problem) => {
  switch (problem) {
    case "A":
      return "rgb(209,86,86)";
    case "B":
      return "rgb(181,98,228)";
    case "C":
      return "rgb(87,98,143)";
    case "D":
      return "rgb(103,226,118)";
    case "E":
      return "rgb(244,228,82)";
    case "F":
      return "rgb(247,138,90)";
    case "G":
      return "rgb(84,129,173)";
    case "H":
      return "rgb(186,185,185)";
    case "I":
      return "rgb(79,184,157)";
    case "J":
      return "rgb(150,211,255)";
    default:
      return "gray";
  }
};


const getContestBoard = async () => {
  const res = (await getContestBoardService({
    contestNum: route.params.contestNum,
    teamNameSelected: teamNameSelected.value,
    schoolSelected: schoolSelected.value,

    currentPage: currentPage.value,
    pageSize: pageSize.value
  })).data
  boardData.value = res.record;
}

onMounted(() =>{
  getContestBoard()
})
</script>

<style scoped>
.leaderboard {
  margin: 0 auto;
  padding: 20px;
}

.result-cell {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100%;
  padding: 5px;
  color: white;
  cursor: pointer;
}

.passed {
  background-color: rgb(61, 171, 61);
}

.not-passed {
  background-color: rgb(255, 125, 125);
}

.submission-symbol {
  font-weight: bold;
  font-size: 1.5em;
}

.submission-details {
  margin-top: 5px;
  font-size: 0.9em;
}

.dialog-footer {
  text-align: right;
}
</style>
